name: Sync to Hugging Face hub
on:
  push:
    branches: [main]
    paths: 
      - 'dashboard/**'
    

  # to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  sync-to-hub:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          lfs: true
      - name: Push to hub
        env:
          TOKEN: ${{ secrets.HF_TOKEN }}
          USERNAME: ${{ vars.HF_USERNAME }}
          STATIC_SPACE: ${{ vars.HF_STATIC_SPACE }}
          
        run:  git push -f https://$USERNAME:$TOKEN@huggingface.co/spaces/$USERNAME/$STATIC_SPACE `git subtree split --prefix dashboard main`:main --force


